include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    always_specify_types: true
    sort_constructors_first: false
    omit_local_variable_types: false
analyzer:
  exclude:
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore
