name: tmdb_movies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.9
  cached_network_image: ^3.3.1
  dio: ^5.4.2+1
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  go_router: ^13.2.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  retrofit: ^4.1.0
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logos/

flutter_native_splash:
  color: "#0D253F"
  image: assets/logos/primary_full_logo.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#0D253F"
    image: assets/logos/primary_full_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/primary_full_logo.png"
  background_color: "#0D253F"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  